services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    ports:
      - 1443:1443
    volumes:
      - WordPress:/var/www/html
    env_file:
      - .env
    secrets:
      - nginx_key
      - nginx_crt

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./requirements/wordpress
    volumes:
      - WordPress:/var/www/html
    env_file:
      - .env
    environment:
      DB_ADMIN_PASSWORD_FILE: /run/secrets/db_admin_password
      WP_DB_USER1_PASSWORD_FILE: /run/secrets/db_user1_password
    secrets:
      - db_admin_password
      - db_user1_password

  mariadb:
    build:
      context: ./requirements/mariadb
    volumes:
      - DB:/var/lib/mysql
    env_file:
      - .env
    environment:
      DB_ADMIN_PASSWORD_FILE: /run/secrets/db_admin_password
      DB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_admin_password
      - db_root_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uhealth -phealthpass -h 127.0.0.1 --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

volumes:
  WordPress:
    name: WordPress
  DB:
    name: DB

#https://docs.docker.com/compose/how-tos/use-secrets/
secrets:
  db_admin_password:
    file: ./secrets/db_admin_password.txt
  db_user1_password:
    file: ./secrets/db_user1_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  nginx_crt:
    file: ./secrets/inception.crt
  nginx_key:
    file: ./secrets/inception.key

networks:
  inception:
    name: inception