services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - 1443:1443
    volumes:
      - WordPress:/var/www/html
    env_file:
      - .env
    secrets:
      - nginx_key
      - nginx_crt

  wordpress:
    build:
      context: ./requirements/wordpress
    volumes:
      - WordPress:/var/www/html
    env_file:
      - .env

  mariadb:
    build:
      context: ./requirements/mariadb
    volumes:
      - DB:/var/lib/mysql
    env_file:
      - .env

volumes:
  WordPress:
    name: WordPress
  DB:
    name: DB

#https://docs.docker.com/compose/how-tos/use-secrets/
secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  nginx_crt:
    file: ./secrets/inception.crt
  nginx_key:
    file: ./secrets/inception.key

networks:
  inception:
    name: inception